[project]
name = "embedding_a_fee_python_example"
version = "1.0.0"
description = "Example: Embedding a Fee using Compass API"
dependencies = [
    "compass-api-sdk",
    "python-dotenv",
    "web3",
    "eth-account",
]

